name: 'TODO to Issue'
on: ['push']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v5'
        with:
          AUTO_ASSIGN: true
          IDENTIFIERS: '[{"name": "TODO", "labels": []}, {"name": "FIXME", "labels": ["bug"]}]'
